//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetProject2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PetProject2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pet_name,pet_photosLink,pet_gender,pet_description,pet_lastUpdated,pet_type,pet_ID,shelter_ID,pet_breed1,pet_breed2,pet_detail,pet_detail/$t
        ///Anibelle,&quot;{&apos;photo&apos;: [{&apos;@size&apos;: &apos;pnt&apos;, &apos;$t&apos;: &apos;http://photos.petfinder.com/photos/pets/38856095/1/?bust=1516454067&amp;width=60&amp;-pnt.jpg&apos;, &apos;@id&apos;: &apos;1&apos;}, {&apos;@size&apos;: &apos;fpm&apos;, &apos;$t&apos;: &apos;http://photos.petfinder.com/photos/pets/38856095/1/?bust=1516454067&amp;width=95&amp;-fpm.jpg&apos;, &apos;@id&apos;: &apos;1&apos;}, {&apos;@size&apos;: &apos;x&apos;, &apos;$t&apos;: &apos;http://photos.petfinder.com/photos/pets/38856095/1/?bust=1516454067&amp;width=500 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pets {
            get {
                return ResourceManager.GetString("Pets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name,address,phone,city,zipCode,email,lat,long,shelterID
        ///Animal Adoptions Ltd.,PO Box 90838,(702) 361-2484,Henderson,89009,teresa@animaladoptionsltd.org,36.0397,-114.9811,NV48
        ///So Nevada Aussie Rescue,286 W Lake Mead Pkwy,(702) 591-6469,Las Vegas,89015,dogrescuelv@hotmail.com,36.0335,-114.9711,NV25
        ///Sin City Saint Rescue,,(702) 896-1049 ,Las Vegas,89012,rescuesaints@gmail.com,36.03,-114.97,NV32
        ///Wagging Tails Rescue,,,Henderson,89052,waggingtailsrescuelv@gmail.com,36.1183,-114.9255,NV184
        ///Paws 4 Love Pet R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Shelters {
            get {
                return ResourceManager.GetString("Shelters", resourceCulture);
            }
        }
    }
}
